### ISSUE TITLE
Add option to disable tests in CMake

### ISSUE THREAD

**Issue by jwbusch** [fgoujeon/signal#1]
Would be nice to have an option to exclude tests from the build tree if a project just wants to only target the header. I'm currently working around this via `add_subdirectory(${SIGNAL_DIR}/fgl_signal)` instead of using the root one. 

Simple as this in the top-level CMakeLists.txt:

```
option(fgl_signal_INCLUDE_TESTS "Include tests in the build" ON)

...

if(fgl_signal_INCLUDE_TESTS)
  add_subdirectory(tests)
endif()
```

Thanks

**Comment by fgoujeon** [comment]
It's done. I've disabled tests by default, since most users aren't interested in running them.

Thank you for your contribution.
