### ISSUE TITLE
variadic using broken on MSVC 15.8.9

### ISSUE THREAD

**Issue by jwbusch** [fgoujeon/signal#2]
https://github.com/fgoujeon/signal/commit/9c1e23a8850660183ed9b0a7498b45a2d8dd22cb

Just a heads up, this latest commit fails to compile on MSVC 15.8.9 (compiler version 19.15.26732.1) , I checked the MSVC 15.9 preview 5 (compiler version 19.16.27023.1) and it's fixed there, so it's a regression/bug in MSVC which will be fixed in the next release.

https://godbolt.org/z/FTmVjB

Godbolt has a slightly older compiler 19.14, but the error message is the same.

Not sure if it's worth it to rollback/workaround, but I'm using an older commit in the meantime. I also wanted to put this here in-case anyone else ran into the issue.

Thanks

**Comment by fgoujeon** [comment]
Thanks for the info, @jwbusch.
I can do without variadic using. I'll just revert the commit.
